# fly.toml app configuration file generated for sudok-server on 2023-06-23T19:27:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sudok-server"
primary_region = "waw"

[http_service]
  PORT = "8080"
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
